#!/bin/sh

cap=$(cat /sys/class/power_supply/BAT0/capacity 2>/dev/null)
status=$(cat /sys/class/power_supply/BAT0/status 2>/dev/null)

[ -z "$cap" ] && exit

case $status in
    "Charging") icon="󰂄 " ;;
    "Discharging")
        if   [ "$cap" -le 20 ]; then icon="󰁻 "
        elif [ "$cap" -le 40 ]; then icon="󰁽 "
        elif [ "$cap" -le 60 ]; then icon="󰁿 "
        elif [ "$cap" -le 80 ]; then icon="󰂁 "
        else icon="󰂂 "
        fi
        ;;
    "Full") icon="󱟢 " ;;
    *) icon=" " ;;
esac

echo "$icon$cap%"
